### ISSUE TITLE
 - Update k8s specs to reflect the "/status" endpoint

### ISSUE THREAD

**Issue by ayasuda-ge** [EC-Release/helmcharts#17]
As solution engineer, I want to update the existing helmchart packages to reflect the latest agent health-probing change, based on v214

**Comment by ramaraosrikakulapu** [comment]
@ayasuda-ge .. Can we close this issue? We now made changes to helm charts to check the health status based on [tcp call](https://github.com/EC-Release/helmcharts/blob/2f25b0ae983315b27ecc55bc75f341888a28fa1c/k8s/agent%2Bhelper/templates/_containerSpec.tpl#L70) and created a [PR](https://github.com/EC-Release/helmcharts/pull/22) for the same.
